### ISSUE TITLE
Trouble running on heroku

### ISSUE THREAD

**Issue by wootwoot1234** [aortbals/southwest-checkin#52]
I'm new to ruby and am having trouble getting this running.

I followed these instructions (https://github.com/aortbals/southwest-checkin/issues/43) and installed southwest-checkin on heroku.  When I click "Add Reservation I get this error:

> We're sorry, but something went wrong.
> If you are the application owner check the logs for more information.

I ran `heroku logs` and this is what it spit out.  What am I missing?

```
2016-05-21T08:28:24.120129+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `call'
2016-05-21T08:28:24.120124+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.1.311/lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
2016-05-21T08:28:24.120130+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_call_callbacks'
2016-05-21T08:28:24.120131+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
2016-05-21T08:28:24.120132+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
2016-05-21T08:28:24.120132+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.1.311/lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
2016-05-21T08:28:24.120129+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:88:in `_run_callbacks'
2016-05-21T08:28:24.120138+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.1.311/lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
2016-05-21T08:28:24.120131+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
2016-05-21T08:28:24.120137+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.1.311/lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
2016-05-21T08:28:24.120139+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/lograge-0.3.5/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
2016-05-21T08:28:24.120140+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/rack/logger.rb:20:in `block in call'
2016-05-21T08:28:24.120141+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:68:in `block in tagged'
2016-05-21T08:28:24.120138+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
2016-05-21T08:28:24.120133+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.1.311/lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
2016-05-21T08:28:24.120142+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:68:in `tagged'
2016-05-21T08:28:24.120141+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/tagged_logging.rb:26:in `tagged'
2016-05-21T08:28:24.120143+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/rack/logger.rb:20:in `call'
2016-05-21T08:28:24.120144+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.1.311/lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
2016-05-21T08:28:24.120144+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/request_id.rb:21:in `call'
2016-05-21T08:28:24.120147+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.1.311/lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
2016-05-21T08:28:24.120145+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
2016-05-21T08:28:24.120136+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
2016-05-21T08:28:24.120143+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.1.311/lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
2016-05-21T08:28:24.120146+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.1.311/lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
2016-05-21T08:28:24.120146+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
2016-05-21T08:28:24.120148+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
2016-05-21T08:28:24.120150+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.1.311/lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
2016-05-21T08:28:24.120148+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.1.311/lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
2016-05-21T08:28:24.120150+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
2016-05-21T08:28:24.120149+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/static.rb:113:in `call'
2016-05-21T08:28:24.120154+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/puma-2.15.3/lib/puma/server.rb:541:in `handle_request'
2016-05-21T08:28:24.120153+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.1.311/lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
2016-05-21T08:28:24.120151+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/newrelic_rpm-3.14.1.311/lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
2016-05-21T08:28:24.120155+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/puma-2.15.3/lib/puma/server.rb:388:in `process_client'
2016-05-21T08:28:24.120156+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/puma-2.15.3/lib/puma/thread_pool.rb:106:in `call'
2016-05-21T08:28:24.120158+00:00 app[web.1]:
2016-05-21T08:28:24.120154+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
2016-05-21T08:28:24.120156+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/puma-2.15.3/lib/puma/server.rb:270:in `block in run'
2016-05-21T08:28:24.120152+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:164:in `call'
2016-05-21T08:28:24.120158+00:00 app[web.1]:
2016-05-21T08:28:24.120157+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/puma-2.15.3/lib/puma/thread_pool.rb:106:in `block in spawn_thread'
2016-05-21T08:28:24.120152+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/engine.rb:518:in `call'
2016-05-21T08:28:24.381221+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=sw-chkin.herokuapp.com request_id=f701c147-3d9e-4344-b45f-f8f01520b1b2 fwd="109.24.166.34" dyno=web.1 connect=5ms service=3ms status=304 bytes=48
2016-05-21T08:29:31.014466+00:00 heroku[router]: at=info method=GET path="/reservations/new" host=sw-chkin.herokuapp.com request_id=eb086ee2-8c62-428f-8986-4b15d69502d4 fwd="109.24.166.34" dyno=web.1 connect=0ms service=10ms status=500 bytes=1669
2016-05-21T08:29:31.153506+00:00 heroku[router]: at=info method=GET path="/reservations/new" host=sw-chkin.herokuapp.com request_id=4b1e4193-aaeb-4cd4-8556-8d2695d52eef fwd="109.24.166.34" dyno=web.1 connect=0ms service=21ms status=500 bytes=1669
2016-05-21T08:29:31.007810+00:00 app[web.1]: PG::UndefinedTable: ERROR:  relation "users" does not exist
2016-05-21T08:29:31.007822+00:00 app[web.1]: LINE 5:                WHERE a.attrelid = '"users"'::regclass
2016-05-21T08:29:31.007824+00:00 app[web.1]:                                           ^
2016-05-21T08:29:31.007824+00:00 app[web.1]: :               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
2016-05-21T08:29:31.007825+00:00 app[web.1]:                      pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
2016-05-21T08:29:31.007826+00:00 app[web.1]:                 FROM pg_attribute a LEFT JOIN pg_attrdef d
2016-05-21T08:29:31.007827+00:00 app[web.1]:                   ON a.attrelid = d.adrelid AND a.attnum = d.adnum
2016-05-21T08:29:31.007827+00:00 app[web.1]:                WHERE a.attrelid = '"users"'::regclass
2016-05-21T08:29:31.007828+00:00 app[web.1]:                  AND a.attnum > 0 AND NOT a.attisdropped
2016-05-21T08:29:31.007829+00:00 app[web.1]:                ORDER BY a.attnum
2016-05-21T08:29:31.007830+00:00 app[web.1]:
2016-05-21T08:29:31.008183+00:00 app[web.1]: {"method":"GET","path":"/reservations/new","format":"html","controller":"reservations","action":"new","status":500,"error":"ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation \"users\" does not exist\nLINE 5:                WHERE a.attrelid = '\"users\"'::regclass\n                                          ^\n:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),\n                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod\n                FROM pg_attribute a LEFT JOIN pg_attrdef d\n                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum\n               WHERE a.attrelid = '\"users\"'::regclass\n                 AND a.attnum > 0 AND NOT a.attisdropped\n               ORDER BY a.attnum\n","duration":3.47}
2016-05-21T08:29:31.009517+00:00 app[web.1]:
2016-05-21T08:29:31.009523+00:00 app[web.1]: ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "users" does not exist
2016-05-21T08:29:31.009524+00:00 app[web.1]: LINE 5:                WHERE a.attrelid = '"users"'::regclass
2016-05-21T08:29:31.009525+00:00 app[web.1]:                                           ^
2016-05-21T08:29:31.009525+00:00 app[web.1]: :               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
2016-05-21T08:29:31.009526+00:00 app[web.1]:                      pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
2016-05-21T08:29:31.009527+00:00 app[web.1]:                 FROM pg_attribute a LEFT JOIN pg_attrdef d
2016-05-21T08:29:31.009527+00:00 app[web.1]:                   ON a.attrelid = d.adrelid AND a.attnum = d.adnum
2016-05-21T08:29:31.009528+00:00 app[web.1]:                WHERE a.attrelid = '"users"'::regclass
2016-05-21T08:29:31.009529+00:00 app[web.1]:                  AND a.attnum > 0 AND NOT a.attisdropped
2016-05-21T08:29:31.009529+00:00 app[web.1]:                ORDER BY a.attnum
2016-05-21T08:29:31.009530+00:00 app[web.1]: ):
2016-05-21T08:29:31.009531+00:00 app[web.1]:   app/controllers/reservations_controller.rb:68:in `authenticate_or_redirect_to_signup!'
2016-05-21T08:29:31.009531+00:00 app[web.1]:
2016-05-21T08:29:31.009532+00:00 app[web.1]:
2016-05-21T08:29:31.136512+00:00 app[web.1]: PG::UndefinedTable: ERROR:  relation "users" does not exist
2016-05-21T08:29:31.136523+00:00 app[web.1]: LINE 5:                WHERE a.attrelid = '"users"'::regclass
2016-05-21T08:29:31.136524+00:00 app[web.1]:                                           ^
2016-05-21T08:29:31.136525+00:00 app[web.1]: :               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
2016-05-21T08:29:31.136526+00:00 app[web.1]:                      pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
2016-05-21T08:29:31.136527+00:00 app[web.1]:                 FROM pg_attribute a LEFT JOIN pg_attrdef d
2016-05-21T08:29:31.136527+00:00 app[web.1]:                   ON a.attrelid = d.adrelid AND a.attnum = d.adnum
2016-05-21T08:29:31.136528+00:00 app[web.1]:                WHERE a.attrelid = '"users"'::regclass
2016-05-21T08:29:31.136528+00:00 app[web.1]:                  AND a.attnum > 0 AND NOT a.attisdropped
2016-05-21T08:29:31.136529+00:00 app[web.1]:                ORDER BY a.attnum
2016-05-21T08:29:31.136530+00:00 app[web.1]:
2016-05-21T08:29:31.136852+00:00 app[web.1]: {"method":"GET","path":"/reservations/new","format":"html","controller":"reservations","action":"new","status":500,"error":"ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation \"users\" does not exist\nLINE 5:                WHERE a.attrelid = '\"users\"'::regclass\n                                          ^\n:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),\n                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod\n                FROM pg_attribute a LEFT JOIN pg_attrdef d\n                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum\n               WHERE a.attrelid = '\"users\"'::regclass\n                 AND a.attnum > 0 AND NOT a.attisdropped\n               ORDER BY a.attnum\n","duration":3.79}
2016-05-21T08:29:31.138356+00:00 app[web.1]:
2016-05-21T08:29:31.138364+00:00 app[web.1]: ActiveRecord::StatementInvalid (PG::UndefinedTable: ERROR:  relation "users" does not exist
2016-05-21T08:29:31.138364+00:00 app[web.1]: LINE 5:                WHERE a.attrelid = '"users"'::regclass
2016-05-21T08:29:31.138365+00:00 app[web.1]:                                           ^
2016-05-21T08:29:31.138366+00:00 app[web.1]: :               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
2016-05-21T08:29:31.138374+00:00 app[web.1]:                      pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
2016-05-21T08:29:31.138375+00:00 app[web.1]:                 FROM pg_attribute a LEFT JOIN pg_attrdef d
2016-05-21T08:29:31.138375+00:00 app[web.1]:                   ON a.attrelid = d.adrelid AND a.attnum = d.adnum
2016-05-21T08:29:31.138376+00:00 app[web.1]:                WHERE a.attrelid = '"users"'::regclass
2016-05-21T08:29:31.138376+00:00 app[web.1]:                  AND a.attnum > 0 AND NOT a.attisdropped
2016-05-21T08:29:31.138377+00:00 app[web.1]:                ORDER BY a.attnum
2016-05-21T08:29:31.138378+00:00 app[web.1]: ):
2016-05-21T08:29:31.138378+00:00 app[web.1]:   app/controllers/reservations_controller.rb:68:in `authenticate_or_redirect_to_signup!'
2016-05-21T08:29:31.138379+00:00 app[web.1]:
2016-05-21T08:29:31.138379+00:00 app[web.1]:
2016-05-21T08:29:31.520217+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=sw-chkin.herokuapp.com request_id=50eb5f2c-5ac7-4edc-82c2-04be7613c05f fwd="109.24.166.34" dyno=web.1 connect=0ms service=1ms status=304 bytes=48
```

**Comment by wootwoot1234** [comment]
I had to run `heroku run rake db:create db:migrate db:seed` to create and seed the databases.
