### ISSUE TITLE
Images/formatting not showing in web interface - FATAL RoutingError

### ISSUE THREAD

**Issue by virento** [aortbals/southwest-checkin#60]
I just installed the latest version from the master.zip file and I have an issue pulling up the website properly.  The website does load, but it's only simple text with no formatting or images.  When I look in the production.log file, I see the following:

```
I, [2016-07-07T09:14:39.124041 #3670]  INFO -- : Started GET "/" for 104.50.85.185 at 2016-07-07 09:14:39 -0500                                [89/1481]
I, [2016-07-07T09:14:39.129661 #3670]  INFO -- : Processing by HomeController#index as HTML
I, [2016-07-07T09:14:39.136184 #3670]  INFO -- :   Rendered home/index.html.erb within layouts/home (3.3ms)
I, [2016-07-07T09:14:39.139992 #3670]  INFO -- :   Rendered shared/_google_tag_manager.erb (0.4ms)
I, [2016-07-07T09:14:39.141776 #3670]  INFO -- :   Rendered components/_header.html.erb (1.3ms)
I, [2016-07-07T09:14:39.144493 #3670]  INFO -- :   Rendered layouts/home.html.erb (9.8ms)
I, [2016-07-07T09:14:39.145313 #3670]  INFO -- : Completed 200 OK in 15ms (Views: 13.0ms | ActiveRecord: 0.0ms)
I, [2016-07-07T09:14:39.682623 #3670]  INFO -- : Started GET "/stylesheets/application.css" for 104.50.85.185 at 2016-07-07 09:14:39 -0500
F, [2016-07-07T09:14:39.687651 #3670] FATAL -- : 
ActionController::RoutingError (No route matches [GET] "/stylesheets/application.css"):
  actionpack (4.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
  railties (4.2.0) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `call'
  newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'                                             [65/1481]
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
  activesupport (4.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
  railties (4.2.0) lib/rails/engine.rb:518:in `call'
  railties (4.2.0) lib/rails/application.rb:164:in `call'
  newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  puma (2.15.3) lib/puma/server.rb:541:in `handle_request'
  puma (2.15.3) lib/puma/server.rb:388:in `process_client'
  puma (2.15.3) lib/puma/server.rb:270:in `block in run'
  puma (2.15.3) lib/puma/thread_pool.rb:106:in `call'
  puma (2.15.3) lib/puma/thread_pool.rb:106:in `block in spawn_thread'


I, [2016-07-07T09:14:39.692753 #3670]  INFO -- : Started GET "/javascripts/application.js" for 104.50.85.185 at 2016-07-07 09:14:39 -0500
F, [2016-07-07T09:14:39.699214 #3670] FATAL -- : 
ActionController::RoutingError (No route matches [GET] "/javascripts/application.js"):
  actionpack (4.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'                                             [41/1481]
  railties (4.2.0) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `call'
  newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
  activesupport (4.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
  railties (4.2.0) lib/rails/engine.rb:518:in `call'
  railties (4.2.0) lib/rails/application.rb:164:in `call'
  newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  puma (2.15.3) lib/puma/server.rb:541:in `handle_request'
  puma (2.15.3) lib/puma/server.rb:388:in `process_client'
  puma (2.15.3) lib/puma/server.rb:270:in `block in run'                                                                                       [17/1481]
  puma (2.15.3) lib/puma/thread_pool.rb:106:in `call'
  puma (2.15.3) lib/puma/thread_pool.rb:106:in `block in spawn_thread'


I, [2016-07-07T09:14:39.766215 #3670]  INFO -- : Started GET "/images/logo.svg" for 104.50.85.185 at 2016-07-07 09:14:39 -0500
F, [2016-07-07T09:14:39.771797 #3670] FATAL -- : 
ActionController::RoutingError (No route matches [GET] "/images/logo.svg"):
  actionpack (4.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
  railties (4.2.0) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `call'
  newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
  activesupport (4.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
  railties (4.2.0) lib/rails/engine.rb:518:in `call'
  railties (4.2.0) lib/rails/application.rb:164:in `call'
  newrelic_rpm (3.14.1.311) lib/new_relic/agent/instrumentation/middleware_tracing.rb:79:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  puma (2.15.3) lib/puma/server.rb:541:in `handle_request'
  puma (2.15.3) lib/puma/server.rb:388:in `process_client'
  puma (2.15.3) lib/puma/server.rb:270:in `block in run'
  puma (2.15.3) lib/puma/thread_pool.rb:106:in `call'
  puma (2.15.3) lib/puma/thread_pool.rb:106:in `block in spawn_thread'
```

As you can see, there is a FATAL RoutingError indicating there isn't a matching route to serve the files being requested.

Any ideas?

**Comment by aortbals** [comment]
Assets must be precompiled when running in production. Please see the [documentation](http://guides.rubyonrails.org/asset_pipeline.html#in-production).
