### ISSUE TITLE
Failing to add Reservation

### ISSUE THREAD

**Issue by mrginogit** [aortbals/southwest-checkin#64]
Having some trouble when attempting to add a reservation.  I input my confirmation number, First Name, and Last Name, and when I submit it, I get an error page: 
`NoMethodError in ReservationsController#create
undefined method `map' for nil:NilClass

Rails.root: C:/Ruby22/southwest-checkin-master

Application Trace | Framework Trace | Full Trace
app/parsers/passengers_parser.rb:9:in `passengers'
app/models/reservation.rb:63:in `create_passengers'
app/controllers/reservations_controller.rb:30:in `create'`

I had this same error when I tried to do the initial "rake dev:prime" to add test data, but figured it was just test data and I could skip that step.  But now it's not working for actual data either =\

I'm pretty new to RoR - any clue on where to start?

**Comment by mrginogit** [comment]
Installed a fresh ubuntu server and tried again from the beginning, all working now.
